spring:
  cache:
    type: simple
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:file:~/h2/testdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
logging:
  level:
      org.springframework.security: info
      org.hibernate.SQL: info
      org.hibernate.type.descriptor.sql: info
eureka:
  client:
    enabled: false

